ARDUINO_DIR   = /Applications/Arduino.app/Contents/Resources/Java
ARDMK_DIR     = /usr/local/opt/arduino-mk
AVR_TOOLS_DIR = /Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr
AVRDUDE_CONF  = /Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/etc/avrdude.conf
MONITOR_PORT  = /dev/tty.usbmodem1411
BOARD_TAG	  = uno
# MONITOR_PORT = /dev/tty.wchusbserial1420
# BOARD_TAG     = nano328

include /usr/local/opt/arduino-mk/Arduino.mk
